apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB: "mongodb://admin:secretpassword@mongodb:27017/"
  PORT: "5000"
  SECRET: "dfkjjkjdfnnkdnkjweruiwiurwefnksknfk7777"
  CLOUD_NAME: "mycloudinarycloudname"
  API_KEY: "1234567890"
  API_SECRET: "mysecretapikey123"
